# Generated by Django 4.2.7 on 2024-03-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_track_alter_task_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrption',
            new_name='description',
        ),
    ]
